functionsDirectory = "/Users/olivertran/Documents/Projects/SpotifyStats/netlify/functions"
functionsDirectoryOrigin = "config"
headersOrigin = "inline"
redirectsOrigin = "inline"

[build]
publish = "/Users/olivertran/Documents/Projects/SpotifyStats/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npx prisma generate && npm run build"
functions = "/Users/olivertran/Documents/Projects/SpotifyStats/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[images]
remote_images = ["^(?:https:\\/\\/i\\.scdn\\.co(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$", "^(?:https:\\/\\/lastfm-img2\\.freetls\\.fastly\\.net(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$", "^(?:https:\\/\\/s34\\.rev\\.sc(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]